services:
  # ---------------- MinIO Service ----------------
  minio_server:
    image: minio/minio:latest
    container_name: minio_server
    hostname: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console/UI port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=bosmuda
      - MINIO_ROOT_PASSWORD=Kelompok6
      - MINIO_DEFAULT_BUCKETS=fp-bigdata
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ---------------- Zookeeper Service ----------------
  zookeeper_server:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper_server
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ---------------- Kafka Service ----------------
  kafka_server:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka_server
    hostname: kafka
    ports:
      - "9092:9092"   # Internal Docker network
      - "29092:29092" # External host access
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      zookeeper_server:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  minio_data:
  zookeeper_data:
  kafka_data: